### ISSUE TITLE
Weird scope expansion for highlighting

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#15]
I don't understand this.

Note: in the first example `(` is, imo, incorrectly underlined and in the second the entire call `len (d2)` is. It should just be `len` in both cases.

![2015-02-18_14 24 17](https://cloud.githubusercontent.com/assets/931051/6247875/17d4e17e-b77a-11e4-952a-6cfc8601e064.png)

![2015-02-18_14 24 43](https://cloud.githubusercontent.com/assets/931051/6247876/1a91aa96-b77a-11e4-83a7-6026d9a21802.png)

![2015-02-18_14 24 48](https://cloud.githubusercontent.com/assets/931051/6247877/1c397f9a-b77a-11e4-9570-c0db84999ea5.png)

**Comment by facelessuser** [comment]
Hmm, haven't seen that before.  I will double check things.  I believe this is simply what the sublime api returns.  I will do some testing before I convent further.

**Comment by facelessuser** [comment]
This is a sublime thing.  Try code below and see what I mean:

```python
sublime.active_window().active_view().extract_scope(sublime.active_window().active_view().sel()[0].begin())
```

I was just exposing that API call.  I guess I could do more post processing on the scope expansion.  Maybe this is new when Jon changed some things (the same things that broke BracketHighlighter).  I know he changed EOF stuff, but maybe it affected other things.  I would have to roll back to an earlier version to be sure.

**Comment by facelessuser** [comment]
I guess the reason this looks weird is because of what sublime decides is the dominant scope, and that is the extent that is shown.  Its like when you have a string with highlighted escapes, sublime may include some of those in the extent and terminate right after one.  I'm not sure what algorithm Jon uses to determine extent, or if it has changed between versions.

Out of curiosity, I would like to compare against an older version when I get a chance.  I may play around with possible other ways to determine scope extent, but I am not really sure how much time I actually am going to invest in this.

**Comment by FichteFoll** [comment]
Tbh I expected that you were just using the API and that is to blame, but I was curios if you had something else to say.

The only other viable way to do scope extracting manually is `view.find_by_selector(selector)` I guess, or you could crawl each character manually which is probably more efficient as you can terminate expanding in one direction as soon as the last scope part doesn't match anymore.

Anyway, sounds like an issue for SublimeTextIssues/Core.

**Comment by facelessuser** [comment]
> There is still view.find_by_selector(selector), or you could crawl each character manually which is probably more efficient as you can terminate expanding in one direction as soon as the last scope part doesn't match anymore.

The big thing I want to avoid is potentially getting the extent of the entire file if the extent is source.language.  I don't want to go character by character for that situation as it will slow things down.  That is why I wanted to rely on the API which executes fast in C opposed to Python.  I will evaluate my options, but I won't promise anything at this point.

**Comment by FichteFoll** [comment]
You currently respect `"highlight_max_size": 100` anyway, don't you?

Besides, you hardly need to use ScopeHunter in situations where performance is really important since it exposes so much information anyway that the user needs to process that first.

**Comment by facelessuser** [comment]
Yeah, I think that was a painting thing that caused ST to lag, but I think I was still getting the full extent from the API.  I will have to play with everything and see how practical it is to use an alternate method.  But you are right, when you're checking scopes, you really aren't trying to do anything else.

**Comment by facelessuser** [comment]
Commit https://github.com/facelessuser/ScopeHunter/commit/dfc735e9b60b4430f95f1d22f2dc103d2c45c0aa should improve scope extent.

**Comment by facelessuser** [comment]
`find_by_selector` seems to work better than `extract_scope`.  I will keep an eye out for performance.  Scope extent isn't directly related to characters with **exactly** the same scope but more dominant scopes range.  For instance, thinks that are just scoped `source.lang` will include strings classes, pretty much the entire file.  This makes since as everything is usually `source.lang`.  So, basically, depending on how the syntax file constructs scopes, will determine how the extent shows up.

`find_by_selector` seems to be more sane it its approach, but it grabs a list of all the matches in the file; for this reason, I mention I will keep an eye on performance to determine if further changes will be needed in the future.

I'm going to consider this closed. Feel free to report issues if you find any with the new method, but also keep in mind what is meant by scope extent.
