### ISSUE TITLE
"ScopeHunter ST3 2.0.2 + certain color scheme" = ST no response

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/ScopeHunter#25]
For example, I personally use [Monokai Soda.tmTheme](https://gist.github.com/jfcherng/1839f2c518873073c06f) from the [Soda color schemes](https://github.com/buymeasoda/soda-theme/#syntax-highlighting-colour-schemes).
After upgrade to `ScopeHunter ST3 2.0.2`, ST starts up and immediately goes no response.

I have tested this on a clean copy of ST 3095.

Unzip ST 3095 portable ->
install package control  ->
install ScopeHunter ->
put `Monokai Soda.tmTheme` in `Packages/my_theme` ->
add `"color_scheme": "Packages/my_theme/Monokai Soda.tmTheme",` to preference ->
restart ST ->
ST goes no response without an error

**Comment by facelessuser** [comment]
So far, I have only tried OSX and I've seen no issue.  I will be able to try your portable windows steps when I get to my windows box.

I admit I am sceptical that the recent release could cause the issue described as the release only strips comments from the scheme in memory before parsing.  I will wait to try your exact steps before making a final statement.

**Comment by jfcherng** [comment]
I can pack my clean but no-response ST into a .zip file without license info if necessary.

**Comment by facelessuser** [comment]
Okay, I tried your exact steps.  I will say this, your specific scheme causes Sublime to hang a little, but only Windows, but I never got a completely unresponsive Sublime where my only option was to close Sublime.  After the scheme loaded, and I waited, responsiveness would return.  But then it would hang on quick panel etc.  This occurred on both portable and installed, but only on Windows.

in ScopeHunter ST3 2.0.1 I fixed a bug where if a specific view has a different color scheme than the global one, ScopeHunter will still pick the right scheme and load the view specific scheme.  Now I did notice that in ScopeHunter ST3 2.0.1, I forgot to exclude widget views (quick panel, find panel, etc.).  This would cause your theme to get reloaded multiple times as a widget (with a different scheme) would take focus and then return focus to the tab view.  Since your theme was getting reloaded multiple times, it would cause the hang to occur multiple times.  So, I just made a release to ignore widgets views https://github.com/facelessuser/ScopeHunter/releases/tag/st3-2.0.3.

I have no idea why your scheme hangs a little, and even less of an idea as to why it only does this on Windows.  I tried a bunch of other schemes, and not a single one caused the issues yours does on Windows.  ScopeHunter will now ignore widgets which should greatly help out, but initial load of your theme still causes a little hang.  I will need to investigate that further.

**Comment by jfcherng** [comment]
Thanks for a fix. Much appreciated.

**Comment by facelessuser** [comment]
It looks like the comment stripping with your file is what is causing the lag.  I probably need a more efficient way to strip the comments.   I will try and speed that up in the next couple of days.

**Comment by facelessuser** [comment]
It's odd that it is Windows specific though....

**Comment by facelessuser** [comment]
Okay, it was really bugging me, so I added a more efficient regex to strip comments.  Your theme seems to parse quickly again.  https://github.com/facelessuser/ScopeHunter/releases/tag/st3-2.0.4.

When you get the release, please let me know if it fixed everything.

**Comment by jfcherng** [comment]
Yes, it works. I feel no noticeable hanging with v2.0.4 ;)

**Comment by facelessuser** [comment]
Nice.  Probably should have seen that coming when I added that regex.  Glad it's fixed now.
