### ISSUE TITLE
python-markdown makes other package break.

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/ScopeHunter#28]
I am using a package named `OmniMarkupPreviewer` which can preview markdown in real-time.
Recently, I found it not working because it occasionally used the `python-markdown` introduced by `ScopeHunter`.
Disabling `ScopeHunter` cannot resolve it but uninstalling `ScopeHunter` resolves.
I am not sure who should be responsible for this (maybe none) so I report both sides.

Ref: https://github.com/timonwong/OmniMarkupPreviewer/issues/85

**Comment by facelessuser** [comment]
Package Control allows dependencies.  All ScopeHunter is doing is using the dependency.  By specifying the dependency for your plugin, PackageControl pulls down the markdown dependency and adds `markdown` to the path.  The dependency is available for anyone to use, even OmniMarkupPreviewer.  

The purpose of dependencies is to allow everyone/anyone to get on the same page and use one global version.  The reason OmniMarkupPreviewer is having trouble is because they vendor their own and then try to add it globally to the path https://github.com/timonwong/OmniMarkupPreviewer/blob/master/OmniMarkupLib/LibraryPathManager.py#L46.  What if everyone tried to do that?  One person wants to load Markdown 2.5, someone else wants to load 2.6 etc.  It would be a mess.

So with a dependency, everyone is using the same.  Now I admit, you don't have control of sticking to an older version in that case, but the alternative is to vendor your own and access it relatively; that is what [Markdown Preview](https://github.com/revolunet/sublimetext-markdown-preview) currently does.

**Comment by jfcherng** [comment]
Thanks for a detail reply. It looks like the `OmniMarkupPreviewer` has to deal with it.
